### ISSUE TITLE
[OTHERS] Should the project specify that it previews only for Github Links

### ISSUE THREAD

**Issue by at-the-vr** [siddhigate/link-preview#5] opened 2023-05-13 17:38 UTC
What I did was use the Test URL method to fetch a twitter URL (obviously it failed) so I thought maybe as a new user someone might try to get hold of something different. Which is why specifying that the endpoint is meant for GitHub links might be good for proper UX.

Additionally I see that the endpoint fails (might be cause of Heroku removing its free tier)

**Comment by siddhigate** [comment] 2023-05-14 05:41
Hey @at-the-vr , 
Get link preview is meant for all kind of links. Its a general solution. After checking why it didn't work for twitter, I found the cause. The twitter profile page is behind an auth wall and may do redirections. This case hasn't been handled and will be fixed. 

Quick question: What made you think it will obviously fail? 

For the endpoint, I have updated the package, but forgot to update the docs on the website. Thanks for pointing it out.

**Comment by at-the-vr** [comment] 2023-05-14 09:12
So in your [controller](https://github.com/siddhigate/link-preview/blob/main/backend/controllers/linkpreviewController.js) and [utils](https://github.com/siddhigate/link-preview/tree/main/backend/utils) your fetching the meta elements 1 by 1, what if 1 of them fails like some website wont have image or an og:url in their meta tags
It will get stuck in the try catch block right ?

**Comment by siddhigate** [comment] 2023-05-14 12:14
> So in your [controller](https://github.com/siddhigate/link-preview/blob/main/backend/controllers/linkpreviewController.js) and [utils](https://github.com/siddhigate/link-preview/tree/main/backend/utils) your fetching the meta elements 1 by 1, what if 1 of them fails like some website wont have image or an og:url in their meta tags It will get stuck in the try catch block right ?

No it won't

**Comment by at-the-vr** [comment] 2023-05-14 13:28
ohh then in that case Issue is not there, i thought it had something to do with Twitter or protected websites like you said

**Closed** 2023-05-14 13:38 UTC
